name: KnightTowns
version: 1.0.0
main: com.knightgost.knighttowns.KnightTowns
api-version: 1.20
author: virendraxd (KnightGost)
commands:
  town:
    description: Town management commands
    usage: /town help
permissions:
  knighttowns.bypass:
    description: Allows bypassing town grief protection (place, break, interact)
    default: op
